### ISSUE TITLE
[4.x] Failing to create a category

### ISSUE THREAD

**Issue by anita-chouhan** [miranj/craft-redirector#1]
### Describe the bug

We recently upgraded the Craft CMS version to 4.7.2 from 3.8.17 on a project. We are using the _Redirector_ plugin in the project and found that category creation is no longer working for Craft either from within an entry or from the _Category Manager_. There is no error notification for it.

### Steps to reproduce

- Setup a Craft CMS version 3.8.1.
- Install and enable the _Redirector_ plugin.
- Upgrade the Craft CMS version to 4.7.2
- Try to create a category.

### Craft CMS version
4.7.2

### Plugin version
dev-dev

### Multi-site?
No

**Comment by rungta** [comment]
Fixed in https://github.com/miranj/craft-redirector/commit/0c6e1a88bf2d833f12332aa88d50e6eb75a38c43
